### ISSUE TITLE
Is KOBAS 3.0 web server not useful?

### ISSUE THREAD

**Issue by oceancongliu** [xmao/kobas#7]
I am using  KOBAS 3 webserver to analysis my DEGs, i uploaded my protein.fasta file to KOBAS 3 webserver.
However, the status of task is  "Your task is in the queue" for 2 days, and no result is load. It is unusual.
My task link is http://kobas.cbi.pku.edu.cn/retrieve/?taskid=cf28cca17314408cbe8709d132a8cd13.

Can you help me to check it.
Thanks.

**Comment by binmao** [comment]
I have got the message ,thank you!     您发给我的信件已经收到。
